### ISSUE TITLE
Pittsburgh arrest 

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/help-desk#1]
## How to help

Read the request below, and try to identify a record of the arrest using the sources below. Please leave a comment if you have questions or a lead on the case.

### Agency
Pittsburgh police, PA courts

### Request

> I've been looking through UJS portal for cases related to arrests at the protest last night.
> 
> I was Legal Observing a protest last night when we saw police running a few blocks away, so we followed them. 
Police had handcuffed a naked woman who was having a mental health episode. An ambulance drove her away. And they arrested a man for standing on the street instead of the sidewalk. We tried to get the man's name, but the police wouldn't let us. 
>
> We're searching the UJS portal through Date Filed. He's a black man in his 20s or 30s. Potential charges are: resisting arrest, terroristic threats, obstructing administration of the law, etc. He was arrested at around 5:40pm on 5/7/24. I bet he's been arraigned by now.

### Potential data sources

https://ujsportal.pacourts.us/CaseSearch
https://data.wprdc.org/dataset/police-incident-blotter (no longer updated)
https://data.wprdc.org/dataset/arrest-data (no longer updated)

**Comment by maxachis** [comment]
Tried tackling this in a cursory manner today. Tried searching on the CaseSearch portal by "date filed" and did today and yesterday. Couldn't find anything that seemed relevant. No arraignments in Allegheny county between 2024-05-08 and 2024-05-08.

A few other challenges:

1. Request doesn't detail where arrest occurred. I assumed "the protest" referred to one reported yesterday downtown. 
2. Most dockets are for civil violations or petty crimes. Makes it difficult to sift through.
3. Possible they were not arraigned yet. Or they were never arraigned. Which, if it shows up in the court system at all, would likely expand the array of possible things to search for.

**Comment by maxachis** [comment]
Final note: WPRDC said "Access to the updated data source will be provided in the future." Unclear if that means the data source will provide access, or WPRDC will set up a system to access it. Either way, we should follow on that and see if we can accelerate, as that'd be quite useful here.
